In [3]:
# Initial imports
import pandas as pd
import hvplot.pandas
from path import Path
import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

In [4]:
# Loading data
file_path = "Resources/TSLA_stock_hist_hourly_2021_11_7.csv"
df_TSLA_stock_hist_hourly_2021_11_7 = pd.read_csv(file_path)
df_TSLA_stock_hist_hourly_2021_11_7.head(10)

,Unnamed: 0,Open,High,Low,Close,Adj Close,Volume,Percent_Day_Change,date_UTC
0,2021-10-28 09:30:00-04:00,1068.305054,1081.000000,1055.209961,1060.359985,1060.359985,8788599,-0.743708,2021-10-28 05:00
1,2021-10-28 10:30:00-04:00,1060.180054,1077.464966,1058.890015,1070.250732,1070.250732,4857422,0.949903,2021-10-28 06:00
2,2021-10-28 11:30:00-04:00,1070.839844,1079.689941,1064.349976,1076.380005,1076.380005,3591916,0.517366,2021-10-28 07:00
3,2021-10-28 12:30:00-04:00,1076.949951,1079.649902,1066.000000,1073.175049,1073.175049,3328912,-0.350518,2021-10-28 08:00
4,2021-10-28 13:30:00-04:00,1073.250000,1074.030029,1067.589966,1072.910034,1072.910034,1543551,-0.031676,2021-10-28 09:00
5,2021-10-28 14:30:00-04:00,1072.770142,1073.249878,1066.109985,1069.935059,1069.935059,1703906,-0.264277,2021-10-28 10:00
6,2021-10-28 15:30:00-04:00,1069.753174,1077.760010,1067.500000,1077.089966,1077.089966,1714894,0.685840,2021-10-28 11:00
7,2021-10-29 09:30:00-04:00,1080.000000,1100.000000,1073.204956,1088.390137,1088.390137,9855755,0.776865,2021-10-29 05:00
8,2021-10-29 10:30:00-04:00,1088.750000,1094.880005,1086.599976,1091.380005,1091.380005,3616633,0.241562,2021-10-29 06:00
9,2021-10-29 11:30:00-04:00,1091.359985,1098.000000,1088.599976,1092.359985,1092.359985,2628858,0.091629,2021-10-29 07:00

In [5]:
# Create a new DataFrame that holds only the cryptocurrencies names.
# holds Percent_Day_Change for TSLA hourly
df_TSLA_stock_hist_hourly_2021_11_7 = pd.DataFrame(df_TSLA_stock_hist_hourly_2021_11_7.Percent_Day_Change)
print(df_TSLA_stock_hist_hourly_2021_11_7.shape)
df_TSLA_stock_hist_hourly_2021_11_7.head()

(49, 1)

   Percent_Day_Change
0           -0.743708
1            0.949903
2            0.517366
3           -0.350518
4           -0.031676