In [125]:
import time
import datetime
import pandas as pd
# Import package
import yfinance as yf

In [129]:
#define function to get stock hist data from today to last year

def getstockhist(ticker):
    #set an automated date for today
    today = datetime.date.today()
    year=2000+int(today.strftime("%y"))
    month=int(today.strftime("%m"))
    day=int(today.strftime("%d"))
    
    #set variable for 2 years ago, for start date
    year_start=2000+int(today.strftime("%y"))-2

    #period 1 is the oldest date, period 2 is the newest date
    period1=int(time.mktime(datetime.datetime(year_start,month,day,1,1).timetuple()))
    period2=int(time.mktime(datetime.datetime(year,month,day,1,1).timetuple()))
    # interval is per day 
    interval="1d"
    query_url=f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1={period1}&period2={period2}&interval={interval}&events=history&includeAdjustedClose=true'
    df=pd.read_csv(query_url)
    df["Percent_Day_Change"]= ((df["Close"]/df["Open"])-1)*100
    # Create the output file (CSV).
    output_data_file = f'resources\{ticker}_stock_hist.csv'
    # Export the City_Data into a CSV.
    df.to_csv(output_data_file)
    return df

In [130]:
# Get the data for the previous 7 days 
def getstockhist_hourly(ticker):
    
    today = datetime.date.today()
    year=2000+int(today.strftime("%y"))
    month=int(today.strftime("%m"))
    day=int(today.strftime("%d"))
    
    df=yf.download(tickers=ticker, period="7d", interval="1h")
    #create new date_utc columns and % day change
    #stock datetime is in NY time, make it into UTC and round to nearest hour . 
    df["Percent_Day_Change"]= ((df["Close"]/df["Open"])-1)*100
    #df["date_UTC"]=df.index
    #df["date_UTC"]=df["date_UTC"].apply(lambda row: row.datetime.timedelta(minutes=270))
    #df["date_UTC"]=df["date_UTC"].apply(lambda row: row.strftime('%Y-%m-%d %H:%M'))
    #df.reset_index()
    
    output_data_file = f'resources\{ticker}_stock_hist_hourly_{year}_{month}_{day}.csv'
    # Export the City_Data into a CSV.
    df.to_csv(output_data_file)
    return df

In [131]:
TSLA_hourly_df=getstockhist_hourly("TSLA")
TSLA_hourly_df

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,Percent_Day_Change
2021-11-02 09:30:00-04:00,1156.599976,1208.589966,1146.000000,1202.310059,1202.310059,20277111,3.952108
2021-11-02 10:30:00-04:00,1202.439941,1202.449951,1172.800049,1177.399902,1177.399902,5034709,-2.082436
2021-11-02 11:30:00-04:00,1177.109985,1181.000000,1161.000000,1162.645508,1162.645508,3998159,-1.228813
2021-11-02 12:30:00-04:00,1162.563843,1172.449951,1152.660034,1166.050171,1166.050171,3864811,0.299883
2021-11-02 13:30:00-04:00,1165.824951,1168.680054,1159.010132,1164.800049,1164.800049,1840610,-0.087912
2021-11-02 14:30:00-04:00,1164.829956,1183.879883,1160.500000,1179.724976,1179.724976,3826987,1.278729
2021-11-02 15:30:00-04:00,1180.000000,1189.259888,1166.750000,1171.849976,1171.849976,3046783,-0.690680
2021-11-03 09:30:00-04:00,1183.609985,1190.199951,1170.030029,1183.329956,1183.329956,8041885,-0.023659
2021-11-03 10:30:00-04:00,1182.699951,1184.723999,1172.280151,1173.474976,1173.474976,2548236,-0.779993
2021-11-03 11:30:00-04:00,1173.319946,1173.800049,1152.619995,1170.324951,1170.324951,3836632,-0.255258
2021-11-03 12:30:00-04:00,1170.500000,1183.000000,1168.000000,1177.339966,1177.339966,3803781,0.584363
2021-11-03 13:30:00-04:00,1177.369995,1178.500000,1165.089966,1174.494995,1174.494995,2856812,-0.244188
2021-11-03 14:30:00-04:00,1174.254761,1208.489868,1171.040039,1197.949951,1197.949951,7777992,2.017892
2021-11-03 15:30:00-04:00,1197.954956,1215.390015,1195.500000,1213.687988,1213.687988,3932824,1.313324
2021-11-04 09:30:00-04:00,1234.410034,1242.000000,1224.820068,1232.696411,1232.696411,8598134,-0.138821
2021-11-04 10:30:00-04:00,1232.619995,1243.489990,1227.500000,1227.500000,1227.500000,3846857,-0.415375
2021-11-04 11:30:00-04:00,1227.658691,1239.699951,1217.000000,1238.780029,1238.780029,3879996,0.905898
2021-11-04 12:30:00-04:00,1239.069946,1241.389893,1231.699951,1235.469971,1235.469971,1960785,-0.290539
2021-11-04 13:30:00-04:00,1235.579956,1238.760010,1228.000000,1235.380005,1235.380005,2038975,-0.016183
2021-11-04 14:30:00-04:00,1235.650024,1240.000000,1227.000000,1228.310059,1228.310059,2175368,-0.594017
2021-11-04 15:30:00-04:00,1228.500000,1237.050049,1225.800049,1229.729980,1229.729980,2221688,0.100121
2021-11-05 09:30:00-04:00,1228.000000,1238.000000,1208.000000,1230.949951,1230.949951,6835874,0.240224
2021-11-05 10:30:00-04:00,1231.069946,1238.929932,1228.535034,1229.219849,1229.219849,2512527,-0.150284
2021-11-05 11:30:00-04:00,1229.010010,1235.300049,1227.188354,1234.250000,1234.250000,1479143,0.426359
2021-11-05 12:30:00-04:00,1234.093506,1239.869995,1220.000000,1222.979980,1222.979980,3527066,-0.900542
2021-11-05 13:30:00-04:00,1222.979980,1231.199951,1222.979980,1229.129883,1229.129883,1685170,0.502862
2021-11-05 14:30:00-04:00,1229.119995,1232.239990,1218.589966,1221.040039,1221.040039,2549845,-0.657377
2021-11-05 15:30:00-04:00,1221.050049,1225.949951,1216.959961,1221.440552,1221.440552,2435693,0.031981
2021-11-08 09:30:00-05:00,1136.000000,1197.000000,1135.000000,1189.204956,1189.204956,16338270,4.683535
2021-11-08 10:30:00-05:00,1188.930054,1194.000000,1178.550049,1188.709961,1188.709961,4594510,-0.018512
2021-11-08 11:30:00-05:00,1188.574951,1190.000000,1181.110107,1186.500000,1186.500000,2091728,-0.174575
2021-11-08 12:30:00-05:00,1186.665039,1194.489990,1185.201050,1187.599976,1187.599976,1730535,0.078787
2021-11-08 13:30:00-05:00,1187.290039,1189.199951,1179.180054,1179.559570,1179.559570,2147664,-0.651102
2021-11-08 14:30:00-05:00,1179.530029,1186.099976,1179.010010,1181.857788,1181.857788,1513944,0.197346
2021-11-08 15:30:00-05:00,1181.670044,1182.329956,1160.000000,1162.729980,1162.729980,3432062,-1.602822
2021-11-09 09:30:00-05:00,1173.599976,1174.500000,1032.000122,1092.655029,1092.655029,20541403,-6.897150
2021-11-09 10:30:00-05:00,1092.650024,1104.530029,1072.620117,1075.000000,1075.000000,5745896,-1.615341
2021-11-09 11:30:00-05:00,1074.890015,1079.489990,1035.000000,1049.640015,1049.640015,8760554,-2.349078
2021-11-09 12:30:00-05:00,1050.000000,1052.589966,1023.640015,1043.839966,1043.839966,6710922,-0.586670
2021-11-09 13:30:00-05:00,1043.829956,1060.930054,1027.290039,1050.189941,1050.189941,5610352,0.609293
2021-11-09 14:30:00-05:00,1050.309937,1052.709961,1024.449951,1024.949951,1024.949951,5163438,-2.414524
2021-11-09 15:30:00-05:00,1024.780029,1031.689941,1011.520020,1023.510010,1023.510010,5229085,-0.123931
2021-11-10 09:30:00-05:00,1010.409973,1074.000000,987.309998,1069.157104,1069.157104,16659921,5.814188
2021-11-10 10:30:00-05:00,1069.000000,1078.099976,1064.628052,1067.339966,1067.339966,4909510,-0.155289
2021-11-10 11:30:00-05:00,1066.849976,1071.000000,1050.800049,1050.800049,1050.800049,2861072,-1.504422
2021-11-10 12:30:00-05:00,1051.310059,1068.250000,1048.000000,1048.326050,1048.326050,3492110,-0.283837
2021-11-10 13:30:00-05:00,1048.324951,1059.869873,1030.000000,1030.650024,1030.650024,2830500,-1.686016
2021-11-10 14:30:00-05:00,1030.110107,1067.000000,1012.500000,1062.250000,1062.250000,6051992,3.120044
2021-11-10 15:30:00-05:00,1062.359985,1075.430054,1052.449951,1067.760010,1067.760010,4117217,0.508305

In [132]:
SPY_hourly_df=getstockhist_hourly("SPY")
SPY_hourly_df.to_csv("resources\SPY_stock_hist_hourly_2021_11_7.csv")

[*********************100%***********************]  1 of 1 completed

In [133]:
TSLA_hist_df=getstockhist("TSLA")

#top 40 rallies 
TSLA_hist_df

,Date,Open,High,Low,Close,Adj Close,Volume,Percent_Day_Change
0,2019-11-11,68.790001,69.837997,68.400002,69.017998,69.017998,49933500,0.331439
1,2019-11-12,69.379997,70.073997,68.807999,69.986000,69.986000,36797000,0.873455
2,2019-11-13,71.000000,71.265999,69.036003,69.222000,69.222000,42100500,-2.504225
3,2019-11-14,69.222000,70.767998,68.582001,69.870003,69.870003,32324500,0.936123
4,2019-11-15,70.127998,70.559998,69.671997,70.433998,70.433998,24045000,0.436345
...,...,...,...,...,...,...,...,...
499,2021-11-03,1177.329956,1215.390015,1152.619995,1213.859985,1213.859985,34628500,3.102786
500,2021-11-04,1234.410034,1243.489990,1217.000000,1229.910034,1229.910034,25397400,-0.364547
501,2021-11-05,1228.000000,1239.869995,1208.000000,1222.089966,1222.089966,21579900,-0.481273
502,2021-11-08,1149.790039,1197.000000,1133.000000,1162.939941,1162.939941,33445700,1.143679
503,2021-11-09,1173.599976,1174.500000,1011.520020,1023.500000,1023.500000,59105800,-12.789705

In [134]:
spy_hist_df=getstockhist("SPY")
spy_hist_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Percent_Day_Change
0,2019-11-11,307.420013,308.540009,307.269989,308.350006,298.298218,35797300,0.302515
1,2019-11-12,308.750000,309.989990,308.149994,309.000000,298.927063,46484600,0.080972
2,2019-11-13,307.910004,309.540009,307.660004,309.100006,299.023773,53917700,0.386477
3,2019-11-14,308.790009,309.640015,308.089996,309.549988,299.459106,51219900,0.246115
4,2019-11-15,311.019989,311.839996,310.260010,311.790009,301.626129,62023600,0.247579

In [135]:
TSLA_hourly_df["date_UTC"]=TSLA_hourly_df.index
TSLA_hourly_df["date_UTC"]=TSLA_hourly_df.index
TSLA_hourly_df["date_UTC"]=TSLA_hourly_df["date_UTC"].apply(lambda row: row-datetime.timedelta(minutes=270))
TSLA_hourly_df["date_UTC"]=TSLA_hourly_df["date_UTC"].apply(lambda row: row.strftime('%Y-%m-%d %H:%M'))
TSLA_hourly_df.head()

,Open,High,Low,Close,Adj Close,Volume,Percent_Day_Change,date_UTC
2021-11-02 09:30:00-04:00,1156.599976,1208.589966,1146.000000,1202.310059,1202.310059,20277111,3.952108,2021-11-02 05:00
2021-11-02 10:30:00-04:00,1202.439941,1202.449951,1172.800049,1177.399902,1177.399902,5034709,-2.082436,2021-11-02 06:00
2021-11-02 11:30:00-04:00,1177.109985,1181.000000,1161.000000,1162.645508,1162.645508,3998159,-1.228813,2021-11-02 07:00
2021-11-02 12:30:00-04:00,1162.563843,1172.449951,1152.660034,1166.050171,1166.050171,3864811,0.299883,2021-11-02 08:00
2021-11-02 13:30:00-04:00,1165.824951,1168.680054,1159.010132,1164.800049,1164.800049,1840610,-0.087912,2021-11-02 09:00

In [136]:
SPY_hourly_df["date_UTC"]=SPY_hourly_df.index
SPY_hourly_df["date_UTC"]=SPY_hourly_df["date_UTC"].apply(lambda row: row+datetime.timedelta(minutes=270))
SPY_hourly_df["date_UTC"]=SPY_hourly_df["date_UTC"].apply(lambda row: row.strftime('%Y-%m-%d %H:%M'))
SPY_hourly_df.head()

,Open,High,Low,Close,Adj Close,Volume,Percent_Day_Change,date_UTC
2021-11-02 09:30:00-04:00,460.399994,461.429993,460.079987,461.220001,461.220001,9882061,0.178108,2021-11-02 14:00
2021-11-02 10:30:00-04:00,461.220001,461.820007,461.079987,461.790009,461.790009,6020298,0.123587,2021-11-02 15:00
2021-11-02 11:30:00-04:00,461.790009,462.222107,461.070007,461.690002,461.690002,5203568,-0.021656,2021-11-02 16:00
2021-11-02 12:30:00-04:00,461.700012,462.100006,461.549988,461.549988,461.549988,3618503,-0.032494,2021-11-02 17:00
2021-11-02 13:30:00-04:00,461.450104,461.785004,461.220093,461.454987,461.454987,4870370,0.001058,2021-11-02 18:00

In [137]:
TSLA_hourly_df.to_csv("TSLA_stock_hist_hourly_2021_11_7.csv")
SPY_hourly_df.to_csv("SPY_stock_hist_hourly_2021_11_7.csv")

In [143]:
tweeter_hour=pd.read_csv("resources\#TSLA_tweet_7days_prior_hist_2021_11_7_perhour.csv")
tweeter_hour["hour"]=tweeter_hour["hour"].astype('timedelta64[h]')
tweeter_hour["day"]=tweeter_hour["day"].astype({'day': 'datetime64[ns]'})
tweeter_hour["date_UTC"]=tweeter_hour["day"]+tweeter_hour["hour"]
tweeter_hour=tweeter_hour.drop(['Unnamed: 0',"hour","day"], axis=1)
tweeter_hour["date_UTC"]=tweeter_hour["date_UTC"].astype({'date_UTC': 'datetime64[ns]'})
tweeter_hour

     Unnamed: 0  Unnamed: 0.1  tweet_counts            date_UTC
0             0             0            22 2021-10-31 18:00:00
1             1             1            30 2021-10-31 19:00:00
2             2             2            16 2021-10-31 20:00:00
3             3             3            34 2021-10-31 21:00:00
4             4             4            93 2021-10-31 22:00:00
..          ...           ...           ...                 ...
164         164           164            30 2021-11-07 14:00:00
165         165           165            57 2021-11-07 15:00:00
166         166           166            36 2021-11-07 16:00:00
167         167           167            27 2021-11-07 17:00:00
168         168           168             1 2021-11-07 17:00:00

[169 rows x 4 columns]

In [146]:
tweeter_hour.dtypes

Unnamed: 0               int64
Unnamed: 0.1             int64
tweet_counts             int64
date_UTC        datetime64[ns]
dtype: object

In [145]:
tweeter_hour.to_csv("resources\#TSLA_tweet_7days_prior_hist_2021_11_7_perhour.csv")